language: php

php:
  - 7.1
  - 7.2

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_OPTS

script:
  - php vendor/bin/phpunit
